### ISSUE TITLE
SSL/HTTPS

### ISSUE THREAD

**Issue by phipier** [jessisena/TreeCheckerApp#9]
We need to make sure that a SSL connection is set up between the Treechecker android application and the Django server.

**Comment by ibesora** [comment]
Hi Pierric,  sorry about being late with this issue. 
The app uses a library called [axios](https://github.com/axios/axios) that supports SSL/HTTPS connections. 
You only need to configure a SSL certificate on your server machine and then change the URLs found in TreeCheckerApp/app/treeChecker/src/actions/urls.js to https instead of http. Our development server was configured to use SSL so we know it works as expected.

**Comment by phipier** [comment]
Great, Thanks.

**Comment by phipier** [comment]
Great, Thanks.
